project:
  type: website
  output-dir: docs
format:
  html:
    theme: spacelab

website: 
  navbar: 
      style: 'docked'
      background: dark
      right:
        - text: 'Programme'
          href: index.md
        - text: 'Ressources'
          href: ressources.html
        - text: 'Séance 1'
          href: https://alexiaschn.github.io/ateliers_ia/seances/intro.html#/title-slide
        - text: 'Séance 2'
          href: https://alexiaschn.github.io/ateliers_ia/seances/correction.html

